# Define a reusable block for common Nginx settings
x-nginx-common: &nginx-common
  build:
    context: ./nginx
    dockerfile: Dockerfile
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  networks:
    - addovedi_net
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8080/nginx-health"]
    interval: 10s
    timeout: 5s
    retries: 3
  depends_on:
    minio:
      condition: service_healthy

services:
  # ----------------------------------------------------------------------------
  # Development Services (profile: dev)
  # ----------------------------------------------------------------------------

  # Nginx reverse proxy for development
  nginx-dev:
    <<: *nginx-common
    container_name: addovedi_nginx_dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "5555:5555" # Prisma Studio
      - "8080:8080" # Health check
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app-dev:
        condition: service_healthy
      prisma-studio:
        condition: service_healthy
    profiles:
      - dev

  # Installs node_modules into a shared volume before the app starts
  installer-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: addovedi_installer_dev
    command: sh -c "pnpm install --frozen-lockfile --ignore-scripts && pnpm db:generate"
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
      - pnpm_store_volume:/app/.pnpm-store
    profiles:
      - dev

  # The main Next.js application for development
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: addovedi_app_dev
    restart: unless-stopped
    entrypoint: ["/app/scripts/dev-entrypoint.sh"]
    command: ["pnpm", "dev"]
    depends_on:
      db:
        condition: service_healthy
      installer-dev:
        condition: service_completed_successfully
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
      - next_cache_volume:/app/.next
      - pnpm_store_volume:/app/.pnpm-store
    expose:
      - "3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      - TZ=UTC
    networks:
      - addovedi_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - dev

  # Prisma Studio for database debugging in development
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: addovedi_prisma_studio
    restart: unless-stopped
    command: pnpm prisma studio --port 5555
    depends_on:
      db:
        condition: service_healthy
      installer-dev:
        condition: service_completed_successfully
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    expose:
      - "5555"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - TZ=UTC
    networks:
      - addovedi_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    profiles:
      - dev

  # ----------------------------------------------------------------------------
  # Production Services (profile: prod)
  # ----------------------------------------------------------------------------

  # Nginx reverse proxy for production
  nginx-prod:
    <<: *nginx-common
    container_name: addovedi_nginx_prod
    restart: always
    ports:
      - "80:80"
      - "8080:8080" # Health check
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - static_public:/app/public:ro
      - static_next:/app/.next/static:ro
    depends_on:
      app-prod:
        condition: service_healthy
    profiles:
      - prod

  # The main Next.js application for production
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - NEXT_PUBLIC_API_URL=/api/
    container_name: addovedi_app_prod
    restart: always
    volumes:
      - static_public:/app/public
      - static_next:/app/.next/static
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    env_file:
      - .env.production
    environment:
      - TZ=UTC
    networks:
      - addovedi_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - prod

  # ----------------------------------------------------------------------------
  # Common Infrastructure Services (used by dev and prod)
  # ----------------------------------------------------------------------------

  # PostgreSQL database
  db:
    image: postgres:17-alpine
    container_name: addovedi_db
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d addovedi"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - addovedi_net


# ----------------------------------------------------------------------------
# Networks and Volumes
# ----------------------------------------------------------------------------

networks:
  addovedi_net:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 172.28.0.0/16
            gateway: 172.28.0.1


volumes:
  postgres_data:
  node_modules_volume:
  next_cache_volume:
  pnpm_store_volume:
  static_public:
  static_next:
