name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd ~/addovedi

            # Pull the latest changes from the main branch
            git pull origin main

            # Create/update the .env file with the secret content
            echo "${{ secrets.ENV_FILE }}" > .env

            # Rebuild and restart the Docker containers
            docker compose up --build -d

            # Run database migrations
            docker compose exec app pnpm prisma migrate deploy